### ISSUE TITLE
[BUG] other login methods are offered on SAML only login, SAML login button not colored

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1377]
## Describe the bug

Although a RC server only allows SAML as authentication method, the app offers the login via e-mail or the creation of an account.

The button of the SAML login is not colored in the configured color. The color of the SAML button is white, so that it is not perceived as a button, but as a hint text. This is a very misleading user guidance!

## To Reproduce

![Screenshot_20191110-175652](https://user-images.githubusercontent.com/8544984/68550736-ea459e00-0405-11ea-894e-d4423eb6bbcd.jpg)

## Devices and Versions

Your Rocket.Chat.Android version: 4.0.4, 4.0.5, 4.1.0
Your Rocket.Chat Server version: 2.2.0 bundle installation

Mobile device model and OS version: OnePlus 7 Android 10

## Additional context
Browser offeres SAML only, color of SAML button is displayed correctly.

**Comment by localguru** [comment]
still in version 4.1.0

**Comment by mddvul22** [comment]
Anyway to escalate this issue.  I would think that any piece of software that shows two login buttons would want to fix that kind of bug.

**Comment by localguru** [comment]
Anything new on it? It confuses my users more and more, especially since the Shibboleth button is only highlighted in white.

**Comment by diegolmello** [comment]
I was hoping someone from the community would fix it, as it's very easy to implement.
Since nobody did it, let's schedule for 4.4.0 and I'll do it myself.

**Comment by localguru** [comment]
@diegolmello Is there already a schedule for a fix? We receive several requests daily from users who overlook the button for login via Shibboleth and try to use their email address or think they need to create an account. This is extremely confusing for normal users. It also makes no sense to offer other authentication methods if the server only offers Sibboleth/SAML and no accounts may be created. It would be great if you could fix it soon.

**Comment by diegolmello** [comment]
@localguru It was fixed yesterday on #1727. I'll release a beta for Experimental later today.

**Comment by localguru** [comment]
@diegolmello This is great, even with the color of the button! Thank you, Diego!

**Comment by diegolmello** [comment]
Kudos to @djorkaeffalexandre (:

**Comment by mddvul22** [comment]
In what version of the stable mobile app should this be appearing?  I have 4.4.0.2107 and am still seeing the problem.  I assume the fix is coming in the next version?

**Comment by diegolmello** [comment]
@mddvul22 Official beta coming next Monday. It's on Experimental beta if you want to try it out.
