### ISSUE TITLE
bug: iOS crashes opening room

### ISSUE THREAD

**Issue by bbrendon** [RocketChat/Rocket.Chat.ReactNative#6685]
### Describe the Bug

Crashes when opening room. Tap on room name, app closes. 

If this message is deleted from the room and the app cache is cleared, the room opens. This just started happening recently so it was either an app update or IOS 26 that triggered it. I also tried upgrading to 7.10.0 but that didn't change anything.

<img width="449" height="49" alt="Image" src="https://github.com/user-attachments/assets/85d74084-c188-409c-919f-4368a584e574" />

### Steps to Reproduce

Crashes when opening room. Tap on room name, app closes. 

### Expected Behavior

App stays open.

### Actual Behavior

App closes

### Rocket.Chat Server Version

7.10.0

### Rocket.Chat App Version

4.6.0.107289

### Device Name

14 pro

### OS Version

26

**Comment by juzser** [comment]
Same, a few rooms make the app crashes when joining. 

Both in iOS and Android.

**Comment by diegolmello** [comment]
Can you please make a request to get the message data, remove any sensitive data and send it here?

If it's a public room, use this https://developer.rocket.chat/apidocs/get-channel-history
It's a private room: https://developer.rocket.chat/apidocs/get-group-history

**Comment by juzser** [comment]
I think I found the issue. 

The memory leaks if you go to the channel with image preview, embedded link preview,... 
I think there are 2 reasons may cause the crashes:
- The image will blur then show up, that effect cause the heavy load? 
- The message with large data, especially with Embedded link preview, quote the message with embedded preview.

Could the team kindly double check?

**Comment by Rohit3523** [comment]
Yesterday we merged a PR to fix the crash issue for the following https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6763

**Comment by juzser** [comment]
@Rohit3523 Thank you, appreciate the effort. 
Do you know when the build will be released?

**Comment by Rohit3523** [comment]
The fix was merged into version 4.66.1, which was released on November 7th.

Could you please check and let me know if you are still facing this issue?

**Comment by juzser** [comment]
Yes, we're still facing the issue. 
Below is the RC ver 4.66.1, I've just installed. 
When I go to a channel with some preview attachments, and scroll, the app crashes. 

[Deleted]

This is an example, actually, anytime you visit a channel or thread with preview image, embedded link,... the app will crash immediately, not even scroll.

**Comment by Rohit3523** [comment]
Thanks for the video, I suggest you to delete the video from the comments as it may contain some sensitive information 🙂.

It's gonna be hard to find the cause of crash without knowing which link preview is crashing the app 😅.

If possible can you please try the following steps.
1. Scroll untill the app crash in the channel.
2. Notice which last message you are able to see before the app crash.
3. Go to web version and try to find the same message.
4. Copy some links above that message and try to send them in a separate channel and check if the app is crashing after going to that channel or not.
5. If the app crash, try to delete one link at a time and open the app (sorry this will take time) and when the app stop crash, you found the link that is causing the crash

If the link is not sensitive, please share that in the comment so I can try to debug it

Thanks

**Comment by juzser** [comment]
@Rohit3523 Thanks for you detailed reply. 
I see it's not because of a specific link, or image. 
Because I tried the way you suggest before, I go to the channel, and remove each message with attachment. 
But it just let you scroll up a bit more, then keep crashing. 
I guess it's memory leaks issue. 

By the way, I always see many error logs in my workspace like this, I don't know if this helps, but I paste here. 
A lot of error logs like this, this is just an example. (_I removed some sensitive url_)

```
{"level":40,"time":"2025-11-10T09:30:28.147Z","pid":1,"hostname":"99d92d8a6e4a","name":"OEmbed","msg":"OEmbed request size exceeded","url":"https://github.com/username/repository-name.git"} 
{"level":50,"time":"2025-11-10T09:31:16.319Z","pid":1,"hostname":"99d92d8a6e4a","name":"OEmbed","msg":"Error fetching url content","err":{"type":"Error","message":"invalid host","stack":"Error: invalid host<br>    at getUrlContent (app/oembed/server/server.ts:79:9)<br>    at getUrlMeta (app/oembed/server/server.ts:188:19)<br>    at getUrlMetaWithCache (app/oembed/server/server.ts:256:21)<br>    at processTicksAndRejections (node:internal/process/task_queues:105:5)<br>    at parseUrl (app/oembed/server/server.ts:146:15)<br>    at Object.rocketUrlParser (app/oembed/server/server.ts:315:37)<br>    at lib/callbacks/callbacksBase.ts:68:13<br>    at lib/callbacks/callbacksBase.ts:76:10<br>    at lib/callbacks/callbacksBase.ts:76:10<br>    at lib/callbacks/callbacksBase.ts:76:10<br>    at lib/callbacks/callbacksBase.ts:76:10<br>    at afterSaveMessage (app/lib/server/lib/afterSaveMessage.ts:14:15)<br>    at sendMessage (app/lib/server/functions/sendMessage.ts:295:2)<br>    at executeSendMessage (app/lib/server/methods/sendMessage.ts:99:10)<br>    at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.ts:157:11)"}} 
```

**Comment by OtavioStasiak** [comment]
@bbrendon  I’d like to know a bit more about the issue.
In the main description, you mentioned:

> If this message is deleted from the room and the app cache is cleared, the room opens. This just started happening recently so it was either an app update or IOS 26 that triggered it. I also tried upgrading to 7.10.0 but that didn't change anything.

In the 4.66.1 mobile version, does deleting this message still fix the issue?

Is there more than one message in this same format?

Could you share an example of the message body (without sensitive data) so I can try to reproduce it?

Thank you!

**Comment by juzser** [comment]
I think this one relates to [#6783 ](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/6783)

> In the 4.66.1 mobile version, does deleting this message still fix the issue?
> Is there more than one message in this same format?
> Could you share an example of the message body (without sensitive data) so I can try to reproduce it?

There are more than one message with preview, embedded, attachments,... So even delete the message, it still occur. 
I tried on almost all Android devices, all crashed. 

Note: The channels have many messages in history.
